query ProjectsQuery {
  allProjectsJson {
    edges {
      node {
        title
        slug
        excerpt
      }
    }
  }
  piChatImage: file(relativePath: { eq: "pichat.jpg" }) {
    childImageSharp {
      fluid(maxWidth: 300) {
        tracedSVG
        aspectRatio
        src
        srcSet
        sizes
      }
    }
  }
}
