fragment sharpImageFields on File {
  childImageSharp {
    fluid(maxWidth: 1200) {
      tracedSVG
      aspectRatio
      src
      srcSet
      sizes
    }
  }
}

query ProjectsQuery {
  allProjectsJson {
    edges {
      node {
        title
        slug
        excerpt
      }
    }
  }
  piChatImage: file(relativePath: { eq: "pichat.jpg" }) {
    ...sharpImageFields
  }
  simonMorphImage: file(relativePath: { eq: "simon-morph.jpg" }) {
    ...sharpImageFields
  }
}
