// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Cx$ReactHooksTemplate = require("../Cx.bs.js");
var SupStyles$ReactHooksTemplate = require("./SupStyles.bs.js");

function str(prim) {
  return prim;
}

function Sup(Props) {
  return React.createElement("div", {
              className: Cx$ReactHooksTemplate.extractSingleStyle((function (prim) {
                      return prim.sup;
                    }), SupStyles$ReactHooksTemplate.externalStyles)
            }, "Sup");
}

var styles = SupStyles$ReactHooksTemplate.externalStyles;

var make = Sup;

var $$default = Sup;

exports.str = str;
exports.styles = styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
