// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var SupModuleCss = require("./Sup.module.css");

var externalStyles = SupModuleCss;

exports.externalStyles = externalStyles;
/* externalStyles Not a pure module */
